In [5]:
import numpy as np
Array1 = np.array([[1,2],[3,4]])
Array2 = np.array([[1,2],[3,4]])

comparison = Array1 == Array2
Compare = comparison.all()

print(Compare)

True


In [6]:
import numpy as np
Array1 = np.array([[1,2],[3,4]])
Array2 = np.array([[1,2],[3,4]])

comparison = Array1 >= Array2
Compare = comparison.all()

print(Compare)

True


In [7]:
import numpy as np
Array1 = np.array([[1,2],[3,4]])
Array2 = np.array([[1,2],[3,4]])

comparison = Array1 > Array2
Compare = comparison.all()

print(Compare)

False


In [8]:
import numpy as np
Array1 = np.array([[1,2],[3,4]])
Array2 = np.array([[1,2],[3,4]])

comparison = Array1 <= Array2
Compare = comparison.all()

print(Compare)

True


In [9]:
import numpy as np
Array1 = np.array([[1,2],[3,4]])
Array2 = np.array([[1,2],[3,4]])

comparison = Array1 < Array2
Compare = comparison.all()

print(Compare)

False


In [10]:
import numpy as np
Array1 = np.array([[1,2],[3,4]])
Array2 = np.array([[1,2],[3,4]])

comparison = Array1 != Array2
Compare = comparison.all()

print(Compare)

False


In [11]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [14]:
import numpy as np
num = np.arange(36)
arr1 = np.reshape(num, [4, 9])
print("Original array:")
print(arr1)
result  = arr1.sum(axis=0)
print("\nSum of all columns:")
print(result)

Original array:
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]

Sum of all columns:
[54 58 62 66 70 74 78 82 86]


In [16]:
import numpy as np
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))

Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25


In [17]:
import numpy as np
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [19]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Hamdan', 'Armaan', 'Karrem', 'Raheem', 'James', 'Ramesh', 'Marwaan', 'Farman', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)

      name  score  attempts qualify
a   Hamdan   12.5         1     yes
b   Armaan    9.0         3      no
c   Karrem   16.5         2     yes
d   Raheem    NaN         3      no
e    James    9.0         2      no
f   Ramesh   20.0         3     yes
g  Marwaan   14.5         1     yes
h   Farman    NaN         1      no
i    Kevin    8.0         2      no
j    Jonas   19.0         1     yes
